#!/bin/sh

OBS_GLCAPTURE_LIB="libobs_glcapture.so"

if [ "$#" -eq 0 ]; then
    programname=`basename "$0"`
    echo "ERROR: No program supplied"
    echo
    echo "Usage: $programname <program>"
    exit 1
fi

LD_PRELOAD="${LD_PRELOAD}:${OBS_GLCAPTURE_LIB}"
exec env LD_PRELOAD="${LD_PRELOAD}" "$@"
